import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import vm from "node:vm";
import { createDiskHarness } from "./disk-files.mjs";
import { openPlugin } from "./plugin-entry-harness.mjs";
import { importedCallCount, loadModule, plain } from "./runtime.mjs";

/** Extracts the actual current SDK script without recreating its callback-reference or owner validation rules. */
function sdkScript(file, name) {
  const source = readFileSync(new URL("../../../../../core/crates/plugin/sdk/src/toolpkg/" + file, import.meta.url), "utf8");
  const signature = "pub fn " + name + "(";
  assert.equal(source.split(signature).length, 2);
  const start = source.indexOf('r#"', source.indexOf(signature)), end = source.indexOf('"#', start + 3);
  assert.ok(start >= 0 && end > start, "The actual SDK registration script must exist");
  return source.slice(start + 3, end);
}

/** Opens only the real SDK registration realm with genuine plugin callbacks; it implements no host business operations. */
function sdkRegistration(plugin) {
  const context = vm.createContext({
    __operitCurrentCallId: "actual-character-bootstrap",
    /** Supplies authenticated registration metadata, not a fake chat, role, memory record or provider. */
    __operitGetCallState(callId) {
      assert.equal(callId, "actual-character-bootstrap");
      return { params: { toolPkgId: "com.operit.character_cards", __operit_toolpkg_api_version: "2.0.0" } };
    },
    /** Exposes the evaluated production main exports to the actual durable-reference resolver. */
    __operitGetActiveModuleExports() { return plugin.main; },
    chatLifecycleHooks: plugin.chatLifecycleHooks,
    chatMessageHooks: plugin.chatMessageHooks,
    hostEventHooks: plugin.hostEventHooks,
    toolLifecycleHooks: plugin.toolLifecycleHooks,
    toolPromptHooks: plugin.toolPromptHooks,
  });
  vm.runInContext("/** Publishes only the existing SDK namespaces in this isolated registration realm. */ globalThis.__operitExpose = function(name, value) { globalThis[name] = value; };", context);
  vm.runInContext(sdkScript("ToolPkgApiRuntimeScript.rs", "buildToolPkgApiRuntimeScript"), context);
  const registration = sdkScript("ToolPkgRegistrationBridge.rs", "buildToolPkgRegistrationBridgeScript");
  assert.equal(registration.split("__OPERIT_TOOLPKG_REGISTRATION_ONLY__").length, 2);
  vm.runInContext(registration.replace("__OPERIT_TOOLPKG_REGISTRATION_ONLY__", "true"), context);
  vm.runInContext("for (const definition of chatLifecycleHooks) ToolPkg.registerChatLifecycleHook(definition); for (const definition of chatMessageHooks) ToolPkg.registerChatMessageHook(definition); for (const definition of hostEventHooks) ToolPkg.registerHostEventHook(definition); for (const definition of toolLifecycleHooks) ToolPkg.registerToolLifecycleHook(definition); for (const definition of toolPromptHooks) ToolPkg.registerToolPromptComposeHook(definition);", context);
  return {
    /** Reads only serialized captures generated by the real SDK from actual main registrations. */
    captured() {
      return JSON.parse(vm.runInContext("JSON.stringify({chatLifecycleHooks:__operitToolPkgRegistrationCapture.chatLifecycleHooks.map(JSON.parse),chatMessageHooks:__operitToolPkgRegistrationCapture.chatMessageHooks.map(JSON.parse),hostEventHooks:__operitToolPkgRegistrationCapture.hostEventHooks.map(JSON.parse),toolLifecycleHooks:__operitToolPkgRegistrationCapture.toolLifecycleHooks.map(JSON.parse),toolPromptHooks:__operitToolPkgRegistrationCapture.toolPromptComposeHooks.map(JSON.parse)})", context));
    },
    /** Attempts the same actually exported initializer a second time to exercise real owner-duplicate rejection. */
    duplicateLifecycle() { return vm.runInContext("ToolPkg.registerChatLifecycleHook(chatLifecycleHooks[0]);", context); },
  };
}

/** Checks registration and export edges on the real main without opening directories or running initialization. */
test("actual openPlugin uniquely registers chat initialization, policies and memory hooks without business IO", async t => {
  const disk = await createDiskHarness(t), plugin = openPlugin(disk);
  assert.equal(importedCallCount("../src/main.ts", "./chat-lifecycle", "registerChatInitialization"), 1);
  assert.equal(importedCallCount("../src/main.ts", "./runtime-tools/policy", "registerToolPolicies"), 1);
  assert.equal(importedCallCount("../src/main.ts", "./memory-jobs/hooks", "registerMemoryJobHooks"), 1);
  assert.equal(typeof loadModule("src/chat-lifecycle.ts").registerChatInitialization, "function");
  const expectations = [
    [plugin.chatLifecycleHooks, "chat-initialization", "beforeChatCreate"],
    [plugin.toolLifecycleHooks, "participant-tool-execution", "toolCallPolicy"],
    [plugin.toolPromptHooks, "participant-tool-visibility", "toolPromptPolicy"],
    [plugin.chatMessageHooks, "memory-candidate-enqueue", "onMemoryMessagePersisted"],
    [plugin.hostEventHooks, "memory-jobs-interval", "onMemoryInterval"],
  ];
  for (const [definitions, id, exportName] of expectations) {
    assert.equal(definitions.length, 1, "Actual bootstrap must register exactly one " + id);
    assert.equal(definitions[0].id, id);
    assert.equal(typeof definitions[0].function, "function");
    assert.equal(definitions[0].function, plugin.main[exportName]);
    assert.deepEqual(Object.entries(plugin.main).filter(
      /** Requires one genuine durable main export, not a guessed callback function name. */
      entry => entry[1] === definitions[0].function,
    ).map(
      /** Preserves the actual export identity consumed by the SDK. */
      entry => entry[0],
    ), [exportName]);
  }
  assert.deepEqual(Object.keys(plugin.chatLifecycleHooks[0]).sort(), ["function", "id"]);
  assert.equal(disk.calls.length, 0, "Main registration must not access files or initialize the service");
  assert.deepEqual(await disk.entries(), [], "No store or job state may be created during registration");
});

/** Resolves every real registered callback through the formal SDK capture/export pipeline, not test callback names. */
test("actual openPlugin lifecycle and policy captures serialize through the real SDK export resolver", async t => {
  const disk = await createDiskHarness(t), plugin = openPlugin(disk), actual = sdkRegistration(plugin);
  assert.deepEqual(actual.captured(), {
    chatLifecycleHooks: [{ id: "chat-initialization", function: "beforeChatCreate" }],
    chatMessageHooks: [{ id: "memory-candidate-enqueue", function: "onMemoryMessagePersisted" }],
    hostEventHooks: [{ id: "memory-jobs-interval", source: "interval", trigger: { kind: "interval", intervalMs: 60000 }, function: "onMemoryInterval" }],
    toolLifecycleHooks: [{ id: "participant-tool-execution", function: "toolCallPolicy" }],
    toolPromptHooks: [{ id: "participant-tool-visibility", function: "toolPromptPolicy" }],
  });
  assert.equal(disk.calls.length, 0, "SDK callback capture must not execute any registered business function");
});

/** Exercises the actual SDK's duplicate-owner rejection using the real main-exported initializer. */
test("real SDK rejects a second lifecycle registration for the actual openPlugin owner", async t => {
  const disk = await createDiskHarness(t), actual = sdkRegistration(openPlugin(disk));
  assert.throws(
    /** Registers the same real initializer twice; a test must not implement a substitute duplicate check. */
    () => actual.duplicateLifecycle(),
    /Duplicate chat lifecycle hook owner: com\.operit\.character_cards/,
  );
  assert.equal(actual.captured().chatLifecycleHooks.length, 1);
  assert.equal(disk.calls.length, 0);
});

/** Invokes the truly registered callback and verifies explicit missing source association rejects without active-state reads. */
test("actual registered initializer rejects a missing source namespace before touching the service", async t => {
  const disk = await createDiskHarness(t), plugin = openPlugin(disk), definition = plugin.chatLifecycleHooks[0];
  const event = {
    eventName: "before_create", creationKind: "new",
    chat: { id: "new-real-draft", title: "Real lifecycle input", workspaceId: null, parentChatId: null },
    sourceChatId: "explicit-source-chat", sourceMessageTimestamp: null, input: null, sourceExtension: null,
  };
  await assert.rejects(definition.function({ eventName: "before_create", eventPayload: plain(event) }), /Explicit sourceChatId has no character namespace extension/);
  assert.equal(disk.calls.length, 0, "Explicit absent source association must never trigger active selection or create storage");
});
